"""Synthesis for the VLSIT flow: script text (code), corners, log → cell count / area.

Backends (chosen by the `synth` tool role: `parse: dc` → Synopsys Design Compiler (default for Synopsys tool sets),
`parse: yosys` → Yosys; `options.synth.backend` overrides)."""

from __future__ import annotations

import os
import re
from pathlib import Path


def backend_for(role_parse, options: dict | None = None) -> str:
    """"dc" (Synopsys Design Compiler / dc_shell) or "yosys"."""
    forced = str(((options or {}).get("synth") or {}).get("backend") or "")
    name = forced or (role_parse if isinstance(role_parse, str) else "")
    return "yosys" if name == "yosys" else "dc"


def script_suffix(backend: str) -> str:
    return ".ys" if backend == "yosys" else ".tcl"


def dc_script(files: list[Path], top: str, library: str | None = None, options: dict | None = None) -> str:
    """The Design Compiler Tcl script: analyze / elaborate / link / compile_ultra and the area / QoR reports.
    `options.synth`: `clock: {port, period_ns}` (constrains the design), `compile: "compile_ultra"` (the command),
    `extra_tcl: [lines]` (e.g. set_app_var search_path, set_max_area, mapped-cell constraints)."""
    cfg = (options or {}).get("synth") or {}
    clk = cfg.get("clock") or {}
    lines = [f"# generated by Q3TUI (vlsit rtl) — top {top}",
             "set_app_var hdlin_enable_presto_for_vhdl false" if False else "set_app_var sh_continue_on_error false"]
    if library:
        lines += [f"set_app_var target_library [list {library}]", f'set_app_var link_library [list "*" {library}]']
    lines += [f"analyze -format sverilog -work WORK {{ {' '.join(str(f) for f in files)} }}",
              f"elaborate {top} -work WORK", f"current_design {top}", "link", "uniquify"]
    if clk.get("port"):
        lines += [f"create_clock -name clk -period {clk.get('period_ns', 10)} [get_ports {clk['port']}]"]
    lines += [str(x) for x in cfg.get("extra_tcl") or []]
    lines += [str(cfg.get("compile") or "compile_ultra"), "report_area", "report_qor", "check_design", "exit"]
    return "\n".join(lines) + "\n"


def script_for(backend: str, files: list[Path], top: str, library: str | None, options: dict | None = None) -> str:
    if backend == "yosys":
        return script_text(files, top, library, int((((options or {}).get("synth") or {}).get("abc_period_ps")) or 5000))
    return dc_script(files, top, library, options)


def script_text(files: list[Path], top: str, liberty: str | None = None, abc_period_ps: int = 5000,
                frontend: str = "read_verilog -sv") -> str:
    """The Yosys script (rtl_generator.md 4a, generalised: the library is optional, the files are listed one by one)."""
    lines = [f"# generated by Q3TUI (vlsit rtl) — top {top}"] + [f"{frontend} {f}" for f in files]
    lines += [f"hierarchy -check -top {top}", "proc", "opt -full", "memory", "opt -full", "techmap", "opt -fast"]
    if liberty:
        lines += [f"dfflibmap -liberty {liberty}", f"abc -liberty {liberty} -D {abc_period_ps}", "opt_clean -purge", f"stat -liberty {liberty}"]
    else:
        lines += ["abc", "opt_clean -purge", "stat"]
    return "\n".join(lines) + "\n"


def corners(options: dict) -> list[dict]:
    """`options.synth.corners: [{name, liberty}]` (paths expand ~ and $ENV); none: one corner without a library."""
    cfg = (options or {}).get("synth") or {}
    out = []
    for c in cfg.get("corners") or []:
        lib = os.path.expandvars(str(c.get("liberty") or c.get("library") or c.get("db") or "")) or None
        out.append({"name": str(c.get("name") or "default"), "liberty": str(Path(lib).expanduser()) if lib else None})
    return out or [{"name": "default", "liberty": None}]


_CELLS = [re.compile(r"Number of cells:\s+(\d+)"), re.compile(r"^\s*(\d+)\s+cells\s*$", re.M)]
_DC_AREA = re.compile(r"Total cell area:\s+([\d.]+)")
_DC_VERSION = re.compile(r"(?:Design Compiler|dc_shell)[^\n]*?\bVersion:?\s+([A-Z]-\d{4}\.\d+(?:-SP\d+)?)|^\s*Version:\s+([A-Z]-\d{4}\.\d+(?:-SP\d+)?)", re.M)
_AREA = re.compile(r"Chip area for (?:top )?module\s+'?\\?([^':\s]+)'?:\s*([\d.]+)")
_VERSION = re.compile(r"Yosys (\d+\.\d+(?:\+\d+)?)")


def parse_stat(log: str, top: str | None = None) -> dict:
    """{cell_count, area_um2, tool} from a Yosys log (the last `stat`, for the top module when given)."""
    cells = None
    for pat in _CELLS:
        found = pat.findall(log)
        if found:
            cells = int(found[-1])
            break
    area = None
    areas = _AREA.findall(log)
    if areas:
        pick = [a for n, a in areas if top and n.lstrip("\\") == top] or [a for _, a in areas]
        area = float(pick[-1])
    v = _VERSION.search(log)
    tool = f"Yosys {v.group(1)}" if v else None
    dc_area = _DC_AREA.findall(log)
    if dc_area:  # Design Compiler: report_area
        area = float(dc_area[-1])
        d = _DC_VERSION.search(log)
        tool = f"Design Compiler {d.group(1) or d.group(2)}" if d else "Design Compiler"
    return {"cell_count": cells, "area_um2": area, "tool": tool}


def attribute_errors(log: str, modules: list[str]) -> dict[str, list[str]]:
    """Error lines of a synthesis log by the module (file) they mention; unattributed ones under ""."""
    out: dict[str, list[str]] = {}
    for line in log.splitlines():
        if not re.search(r"\bERROR\b|^\s*Error:", line):
            continue
        owner = next((m for m in modules if re.search(rf"\b{re.escape(m)}(\.sv)?\b", line)), "")
        out.setdefault(owner, []).append(line.strip()[:300])
    return out
