"""Timing constraints of the FPGA flow: `sdc/sdc.json` (what the user edits) → `sdc/*.tcl` (rendered by code).

    sdc/sdc.json         clocks, I/O delay budget, clock groups, path exceptions, environment (the source of truth)
    sdc/clocks.tcl       create_clock, set_clock_uncertainty
    sdc/clock_groups.tcl set_clock_groups (empty comment when there is one clock)
    sdc/exceptions.tcl   false / multicycle paths, min / max delay overrides
    sdc/io_constraints.tcl  set_input_delay / set_output_delay for every port of the top module
    sdc/env.tcl          driving cell, load, max fanout / transition (ASIC tools; the FPGA tools skip it)
    sdc/sdc.tcl          sources the files above in this order (env.tcl only where its commands exist)

The files are plain SDC Tcl, so Vivado (`read_xdc`) and Design Compiler (`source`) read the same constraints."""

from __future__ import annotations

import re
from pathlib import Path

from pydantic import BaseModel, Field

FILES = ("clocks.tcl", "clock_groups.tcl", "exceptions.tcl", "io_constraints.tcl", "env.tcl", "sdc.tcl")
CLOCK_NAME = re.compile(r"(^|_)(clk|clock)($|_)", re.I)
HEADER = "# generated by Q3TUI (fpga sdc) from sdc/sdc.json — edit that file (or use the TUI), not this one\n"


class Clock(BaseModel):
    name: str
    port: str
    period_ns: float = 10.0
    uncertainty_ns: float = 0.0
    duty_pct: float = 50.0

    @property
    def freq_mhz(self) -> float:
        return round(1000.0 / self.period_ns, 3)


class ClockGroup(BaseModel):
    kind: str = "asynchronous"  # asynchronous | logically_exclusive | physically_exclusive
    groups: list[list[str]] = Field(default_factory=list)  # clock names


class IOBudget(BaseModel):
    clock: str = ""  # default: the first clock
    input_pct: float = 30.0  # input delay = this % of the clock period (max); min is 0
    output_pct: float = 30.0
    exclude: list[str] = Field(default_factory=list)  # ports left unconstrained (resets are false paths)


class PathException(BaseModel):
    kind: str  # false_path | multicycle | max_delay | min_delay
    from_: str = Field("", alias="from")  # clock, port or pin name; empty: not used
    to: str = ""
    through: str = ""
    value: float | None = None  # multicycle: cycles; max/min delay: ns
    note: str = ""

    model_config = {"populate_by_name": True}


class Env(BaseModel):
    driving_cell: str | None = None
    load_pf: float | None = None
    max_fanout: int | None = None
    max_transition_ns: float | None = None


class SdcConfig(BaseModel):
    clocks: list[Clock] = Field(default_factory=list)
    io: IOBudget = Field(default_factory=IOBudget)
    clock_groups: list[ClockGroup] = Field(default_factory=list)
    exceptions: list[PathException] = Field(default_factory=list)
    env: Env = Field(default_factory=Env)
    resets: list[str] = Field(default_factory=list)  # asynchronous reset inputs: false paths from them


def sdc_dir(project) -> Path:
    return project.root / "sdc"


def config_path(project) -> Path:
    return sdc_dir(project) / "sdc.json"


def load(project) -> SdcConfig | None:
    p = config_path(project)
    return SdcConfig.model_validate_json(p.read_text()) if p.is_file() else None


def save(project, cfg: SdcConfig) -> Path:
    p = config_path(project)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(cfg.model_dump_json(indent=2, by_alias=True, exclude_defaults=False) + "\n")
    return p


# -- ports of the top module ----------------------------------------------------------------------------------


def top_ports(project, filelist: Path, top: str) -> list[dict]:
    """[{name, dir, vector}] of the top module (pyslang; cached by the content of the RTL files)."""
    from q3tui.core.project import read_json, sha256_json, write_json
    from q3tui.hdl.filelist import parse_filelist

    fl = parse_filelist(filelist, base_dir=project.root)
    key = sha256_json({"top": top, "files": [(str(f), f.read_text()) for f in fl.all_sources() if f.is_file()]})
    cache = project.state_dir / "cache" / "fpga_ports.json"
    saved = read_json(cache)
    if saved and saved.get("key") == key:
        return saved["ports"]
    from q3tui.hdl.parse import parse_design

    design = parse_design(fl, top)
    info = design.modules.get(top)
    if info is None:
        raise ValueError(f"top module '{top}' not found in {filelist}")
    ports = [{"name": p.name, "dir": p.direction, "vector": "[" in p.type} for p in info.ports]
    project.ensure_state_dir()
    write_json(cache, {"key": key, "ports": ports})
    return ports


# -- defaults ----------------------------------------------------------------------------------------------------


_MHZ = re.compile(r"(\d+(?:\.\d+)?)\s*(MHz|GHz)", re.I)
_NS = re.compile(r"(\d+(?:\.\d+)?)\s*ns\s*period|period[^.\n]{0,20}?(\d+(?:\.\d+)?)\s*ns", re.I)


def period_from_spec(text: str) -> float | None:
    """The clock period the spec states ("target frequency 100 MHz", "10 ns period"), near a mention of the clock."""
    for line in text.splitlines():
        if not re.search(r"clock|clk|frequency", line, re.I):
            continue
        m = _MHZ.search(line)
        if m:
            mhz = float(m.group(1)) * (1000.0 if m.group(2).lower() == "ghz" else 1.0)
            if mhz > 0:
                return round(1000.0 / mhz, 4)
        m = _NS.search(line)
        if m:
            return float(m.group(1) or m.group(2))
    return None


def default_config(ports: list[dict], spec_text: str = "", period_ns: float | None = None) -> SdcConfig:
    """Clocks = input ports named like a clock; every reset input is an asynchronous-reset false path."""
    from q3tui.hdl.parse import _RESET_NAME_RE

    period = period_ns or period_from_spec(spec_text) or 10.0
    ins = [p["name"] for p in ports if p["dir"] == "input"]
    clocks = [Clock(name=n, port=n, period_ns=period) for n in ins if CLOCK_NAME.search(n)]
    resets = [n for n in ins if _RESET_NAME_RE.search(n) and n not in {c.port for c in clocks}]
    return SdcConfig(clocks=clocks, io=IOBudget(clock=clocks[0].name if clocks else ""), resets=resets)


def port_problems(cfg: SdcConfig, ports: list[dict]) -> list[str]:
    """What the SDC names that the top module does not have: clock ports, resets, ports left out of the I/O budget."""
    ins = {p["name"] for p in ports if p["dir"] == "input"}
    every = {p["name"] for p in ports}
    hint = f" (inputs: {', '.join(sorted(ins)[:6])}{', …' if len(ins) > 6 else ''})"
    out = [f"clock {c.name}: port '{c.port}' is not an input" + hint for c in cfg.clocks if c.port not in ins]
    out += [f"reset '{r}' is not an input" for r in cfg.resets if r not in ins]
    out += [f"io.exclude '{x}' is not a port" for x in cfg.io.exclude if x not in every]
    return out


# -- rendering --------------------------------------------------------------------------------------------------


def _num(v: float) -> str:
    return f"{v:.4f}".rstrip("0").rstrip(".") if v != int(v) else str(int(v))


def _ports(names: list[str], vec: dict[str, bool]) -> str:
    return "[get_ports {" + " ".join(f"{n}[*]" if vec.get(n) else n for n in names) + "}]"


def _clocks_tcl(cfg: SdcConfig) -> str:
    out = [HEADER, "# Clocks: one per clock input of the top module.\n"]
    for c in cfg.clocks:
        wave = ""
        if abs(c.duty_pct - 50.0) > 1e-6:
            wave = f" -waveform {{0 {_num(c.period_ns * c.duty_pct / 100.0)}}}"
        out.append(f"create_clock -name {c.name} -period {_num(c.period_ns)}{wave} [get_ports {c.port}]"
                   f"  ;# {_num(c.freq_mhz)} MHz\n")
        if c.uncertainty_ns:
            out.append(f"set_clock_uncertainty {_num(c.uncertainty_ns)} [get_clocks {c.name}]\n")
    if not cfg.clocks:
        out.append("# (no clock: none of the top module's inputs is named like one — add one with the SDC editor)\n")
    return "".join(out)


def _groups_tcl(cfg: SdcConfig) -> str:
    out = [HEADER, "# Relations between clocks.\n"]
    for g in cfg.clock_groups:
        groups = " ".join(f"-group [get_clocks {{{' '.join(grp)}}}]" for grp in g.groups if grp)
        out.append(f"set_clock_groups -{g.kind} {groups}\n")
    if not cfg.clock_groups:
        out.append(f"# single clock domain ({len(cfg.clocks)} clock{'s' if len(cfg.clocks) != 1 else ''}): no clock groups\n")
    return "".join(out)


def _ref(kind: str, name: str) -> str:
    return f"[get_clocks {name}]" if kind == "clock" else f"[get_ports {name}]"


def _exceptions_tcl(cfg: SdcConfig) -> str:
    out = [HEADER, "# Path exceptions.\n"]
    clocks = {c.name for c in cfg.clocks}

    def ep(opt: str, name: str) -> str:
        return f" {opt} {_ref('clock' if name in clocks else 'port', name)}" if name else ""

    for r in cfg.resets:
        out.append(f"set_false_path -from [get_ports {r}]  ;# asynchronous reset input\n")
    for e in cfg.exceptions:
        note = f"  ;# {e.note}" if e.note else ""
        args = ep("-from", e.from_) + ep("-to", e.to) + (f" -through [get_pins {e.through}]" if e.through else "")
        if e.kind == "false_path":
            out.append(f"set_false_path{args}{note}\n")
        elif e.kind == "multicycle":
            n = int(e.value or 2)
            out.append(f"set_multicycle_path {n} -setup{args}{note}\n")
            out.append(f"set_multicycle_path {n - 1} -hold{args}\n")
        elif e.kind in ("max_delay", "min_delay"):
            out.append(f"set_{e.kind} {_num(e.value or 0.0)}{args}{note}\n")
        else:
            raise ValueError(f"unknown path exception kind '{e.kind}' (false_path, multicycle, max_delay, min_delay)")
    if not cfg.resets and not cfg.exceptions:
        out.append("# (none)\n")
    return "".join(out)


def _io_tcl(cfg: SdcConfig, ports: list[dict]) -> str:
    vec = {p["name"]: p["vector"] for p in ports}
    clk = next((c for c in cfg.clocks if c.name == cfg.io.clock), cfg.clocks[0] if cfg.clocks else None)
    out = [HEADER, "# I/O delays: a share of the clock period is spent outside the block.\n"]
    if clk is None:
        return "".join(out) + "# (no clock: I/O delays need one)\n"
    skip = set(cfg.io.exclude) | set(cfg.resets) | {c.port for c in cfg.clocks}
    ins = [p["name"] for p in ports if p["dir"] == "input" and p["name"] not in skip]
    outs = [p["name"] for p in ports if p["dir"] == "output" and p["name"] not in skip]
    d_in, d_out = clk.period_ns * cfg.io.input_pct / 100.0, clk.period_ns * cfg.io.output_pct / 100.0
    ref = f"-clock [get_clocks {clk.name}]"
    if ins:
        out.append(f"set_input_delay {ref} -max {_num(d_in)} {_ports(ins, vec)}  ;# {_num(cfg.io.input_pct)}% of {_num(clk.period_ns)} ns\n")
        out.append(f"set_input_delay {ref} -min 0 {_ports(ins, vec)}\n")
    if outs:
        out.append(f"set_output_delay {ref} -max {_num(d_out)} {_ports(outs, vec)}  ;# {_num(cfg.io.output_pct)}% of {_num(clk.period_ns)} ns\n")
        out.append(f"set_output_delay {ref} -min 0 {_ports(outs, vec)}\n")
    return "".join(out)


def _env_tcl(cfg: SdcConfig) -> str:
    e = cfg.env
    out = [HEADER, "# Operating environment (ASIC tools; the FPGA tools do not have these commands).\n"]
    if e.driving_cell:
        out.append(f"set_driving_cell -lib_cell {e.driving_cell} [all_inputs]\n")
    if e.load_pf is not None:
        out.append(f"set_load {_num(e.load_pf)} [all_outputs]\n")
    if e.max_fanout is not None:
        out.append(f"set_max_fanout {e.max_fanout} [current_design]\n")
    if e.max_transition_ns is not None:
        out.append(f"set_max_transition {_num(e.max_transition_ns)} [current_design]\n")
    if len(out) == 2:
        out.append("# (none)\n")
    return "".join(out)


MASTER = HEADER + """set _d [file dirname [info script]]
source $_d/clocks.tcl
source $_d/clock_groups.tcl
source $_d/io_constraints.tcl
source $_d/exceptions.tcl
if {[llength [info commands set_driving_cell]]} { source $_d/env.tcl }
"""


def render(cfg: SdcConfig, ports: list[dict]) -> dict[str, str]:
    """{file name: text} of every generated SDC file."""
    names = {c.name for c in cfg.clocks}
    for g in cfg.clock_groups:
        for grp in g.groups:
            bad = [n for n in grp if n not in names]
            if bad:
                raise ValueError(f"clock group names unknown clock(s): {', '.join(bad)}")
    if cfg.io.clock and cfg.clocks and cfg.io.clock not in names:
        raise ValueError(f"io.clock '{cfg.io.clock}' is not a clock")
    return {"clocks.tcl": _clocks_tcl(cfg), "clock_groups.tcl": _groups_tcl(cfg), "exceptions.tcl": _exceptions_tcl(cfg),
            "io_constraints.tcl": _io_tcl(cfg, ports), "env.tcl": _env_tcl(cfg), "sdc.tcl": MASTER}


def write(project, cfg: SdcConfig, ports: list[dict]) -> list[Path]:
    """Render into sdc/ (backing up what is overwritten); returns the files written."""
    files = render(cfg, ports)
    d = sdc_dir(project)
    d.mkdir(parents=True, exist_ok=True)
    project.backup([d / n for n, t in files.items() if (d / n).is_file() and (d / n).read_text() != t])
    out = []
    for name, text in files.items():
        p = d / name
        if not p.is_file() or p.read_text() != text:
            p.write_text(text)
            out.append(p)
    return out


# -- editing (the TUI's SDC tab, the assistant, Ops) --------------------------------------------------------------------

_CLOCK_FIELDS = {"period_ns": float, "freq_mhz": float, "uncertainty_ns": float, "duty_pct": float, "port": str}
_ENV_FIELDS = {"driving_cell": str, "load_pf": float, "max_fanout": int, "max_transition_ns": float}


def rows(cfg: SdcConfig) -> list[tuple[str, str, str]]:
    """[(key, setting, value)] — what the SDC tab lists; `apply_edit(cfg, key, value)` changes one."""
    out: list[tuple[str, str, str]] = []
    for c in cfg.clocks:
        out += [(f"clock.{c.name}.freq_mhz", f"clock {c.name}: frequency (MHz)", f"{c.freq_mhz:g}"),
                (f"clock.{c.name}.period_ns", f"clock {c.name}: period (ns)", f"{c.period_ns:g}"),
                (f"clock.{c.name}.uncertainty_ns", f"clock {c.name}: uncertainty (ns)", f"{c.uncertainty_ns:g}"),
                (f"clock.{c.name}.duty_pct", f"clock {c.name}: duty cycle (%)", f"{c.duty_pct:g}")]
    out += [("io.input_pct", "input delay (% of period)", f"{cfg.io.input_pct:g}"),
            ("io.output_pct", "output delay (% of period)", f"{cfg.io.output_pct:g}"),
            ("io.clock", "I/O reference clock", cfg.io.clock),
            ("io.exclude", "ports without I/O delay", ", ".join(cfg.io.exclude)),
            ("resets", "asynchronous resets (false paths)", ", ".join(cfg.resets))]
    out += [(f"exception.{i}", f"exception {i + 1}: {e.kind}", " ".join(x for x in (
        f"from {e.from_}" if e.from_ else "", f"to {e.to}" if e.to else "", f"through {e.through}" if e.through else "",
        f"= {e.value:g}" if e.value is not None else "", f"({e.note})" if e.note else "") if x)) for i, e in enumerate(cfg.exceptions)]
    out += [(f"group.{i}", f"clock group {i + 1}: {g.kind}", " | ".join(",".join(x) for x in g.groups)) for i, g in enumerate(cfg.clock_groups)]
    out += [(f"env.{k}", f"environment: {k}", "" if getattr(cfg.env, k) is None else str(getattr(cfg.env, k))) for k in _ENV_FIELDS]
    return out


def _conv(kind, value: str, key: str):
    v = value.strip()
    try:
        return kind(v)
    except ValueError as exc:
        raise ValueError(f"{key}: '{value}' is not a {'number' if kind in (float, int) else 'valid value'}") from exc


def _names(text: str) -> list[str]:
    return [x for x in re.split(r"[,\s]+", text.strip()) if x]


def apply_edit(cfg: SdcConfig, key: str, value: str) -> str:
    """Change one setting (keys of `rows`; an empty value clears an optional one); returns what changed."""
    parts = key.split(".")
    if parts[0] == "clock" and len(parts) == 3:
        clk = next((c for c in cfg.clocks if c.name == parts[1]), None)
        if clk is None or parts[2] not in _CLOCK_FIELDS:
            raise ValueError(f"unknown setting '{key}' (clocks: {', '.join(c.name for c in cfg.clocks) or 'none'})")
        field = parts[2]
        if field == "freq_mhz":
            mhz = _conv(float, value, key)
            if mhz <= 0:
                raise ValueError("the frequency must be positive")
            clk.period_ns = round(1000.0 / mhz, 4)
        else:
            new = _conv(_CLOCK_FIELDS[field], value, key)
            if field == "period_ns" and new <= 0:
                raise ValueError("the period must be positive")
            if field == "duty_pct" and not 0 < new < 100:
                raise ValueError("the duty cycle is between 0 and 100 %")
            setattr(clk, field, new)
        return f"clock {clk.name}: {clk.period_ns:g} ns ({clk.freq_mhz:g} MHz)"
    if key in ("io.input_pct", "io.output_pct"):
        new = _conv(float, value, key)
        if not 0 <= new <= 100:
            raise ValueError("a share of the period is between 0 and 100 %")
        setattr(cfg.io, key.split(".")[1], new)
        return f"{key} = {new:g}"
    if key == "io.clock":
        if value.strip() and value.strip() not in {c.name for c in cfg.clocks}:
            raise ValueError(f"'{value}' is not a clock ({', '.join(c.name for c in cfg.clocks)})")
        cfg.io.clock = value.strip()
        return f"I/O reference clock = {cfg.io.clock or 'first clock'}"
    if key == "io.exclude":
        cfg.io.exclude = _names(value)
        return f"ports without I/O delay: {', '.join(cfg.io.exclude) or 'none'}"
    if key == "resets":
        cfg.resets = _names(value)
        return f"asynchronous resets: {', '.join(cfg.resets) or 'none'}"
    if parts[0] == "env" and len(parts) == 2 and parts[1] in _ENV_FIELDS:
        setattr(cfg.env, parts[1], _conv(_ENV_FIELDS[parts[1]], value, key) if value.strip() else None)
        return f"environment {parts[1]} = {getattr(cfg.env, parts[1])}"
    raise ValueError(f"unknown setting '{key}'")


def add_item(cfg: SdcConfig, what: str, text: str) -> str:
    """Add a clock (`name port period_ns`), an exception (`false_path from=A to=B through=P value=2 note…`: kind first) or a
    clock group (`asynchronous clkA | clkB`)."""
    if what == "clock":
        bits = text.split()
        if len(bits) < 2:
            raise ValueError("a clock is `name port [period_ns]`")
        name, port = bits[0], bits[1]
        if any(c.name == name for c in cfg.clocks):
            raise ValueError(f"clock '{name}' exists")
        cfg.clocks.append(Clock(name=name, port=port, period_ns=float(bits[2]) if len(bits) > 2 else 10.0))
        if not cfg.io.clock:
            cfg.io.clock = name
        return f"added clock {name}"
    if what == "exception":
        kind, *rest = text.split(None, 1)
        kv = dict(re.findall(r"(\w+)=(\S+)", rest[0] if rest else ""))
        note = re.sub(r"\w+=\S+", "", rest[0] if rest else "").strip()
        value = float(kv["value"]) if "value" in kv else None
        exc = PathException.model_validate({"kind": kind, "from": kv.get("from", ""), "to": kv.get("to", ""),
                                            "through": kv.get("through", ""), "value": value, "note": note})
        if kind not in ("false_path", "multicycle", "max_delay", "min_delay"):
            raise ValueError("exception kinds: false_path, multicycle, max_delay, min_delay")
        if kind in ("multicycle", "max_delay", "min_delay") and value is None:
            raise ValueError(f"{kind} needs value=<n>")
        if not (exc.from_ or exc.to or exc.through):
            raise ValueError("an exception needs from= / to= / through=")
        cfg.exceptions.append(exc)
        return f"added {kind}"
    if what == "group":
        kind, _, rest = text.partition(" ")
        if kind not in ("asynchronous", "logically_exclusive", "physically_exclusive"):
            raise ValueError("a clock group is `asynchronous|logically_exclusive|physically_exclusive clkA | clkB [| clkC]`")
        groups = [_names(g) for g in rest.split("|") if g.strip()]
        if len(groups) < 2:
            raise ValueError("a clock group needs two or more groups separated by |")
        cfg.clock_groups.append(ClockGroup(kind=kind, groups=groups))
        return f"added {kind} clock group"
    raise ValueError("add: clock, exception or group")


def remove_item(cfg: SdcConfig, key: str) -> str:
    """Remove an `exception.N` / `group.N` row or a `clock.<name>.*` clock."""
    parts = key.split(".")
    if parts[0] in ("exception", "group") and len(parts) == 2 and parts[1].isdigit():
        items = cfg.exceptions if parts[0] == "exception" else cfg.clock_groups
        if int(parts[1]) >= len(items):
            raise ValueError(f"no {parts[0]} {int(parts[1]) + 1}")
        items.pop(int(parts[1]))
        return f"removed {parts[0]} {int(parts[1]) + 1}"
    if parts[0] == "clock" and len(parts) >= 2:
        if len(cfg.clocks) <= 1:
            raise ValueError("the last clock cannot be removed")
        cfg.clocks = [c for c in cfg.clocks if c.name != parts[1]]
        cfg.clock_groups = [g for g in cfg.clock_groups if all(n in {c.name for c in cfg.clocks} for grp in g.groups for n in grp)]
        if cfg.io.clock == parts[1]:
            cfg.io.clock = cfg.clocks[0].name
        return f"removed clock {parts[1]}"
    raise ValueError(f"'{key}' cannot be removed (exceptions, clock groups and clocks can)")


def replace_item(cfg: SdcConfig, key: str, text: str) -> str:
    """Replace an `exception.N` / `group.N` by what `add_item` would add for `text` (nothing changes when `text` is invalid)."""
    parts = key.split(".")
    if parts[0] not in ("exception", "group") or len(parts) != 2 or not parts[1].isdigit():
        raise ValueError("only an exception or a clock group is replaced (exception.N, group.N)")
    items = cfg.exceptions if parts[0] == "exception" else cfg.clock_groups
    i = int(parts[1])
    if i >= len(items):
        raise ValueError(f"no {parts[0]} {i + 1}")
    add_item(cfg, parts[0], text)
    items[i] = items.pop()
    return f"changed {parts[0]} {i + 1}"
