"""Vivado for the FPGA flow: the out-of-context synthesis script (code) and the report readers (code).

The script reads the RTL and the SDC files of `sdc/`, runs `synth_design -mode out_of_context` (no pins, no wrapper: the block
alone) and writes `utilization.rpt` / `timing.rpt` / `check_timing.rpt` next to itself; `parse_utilization` and
`parse_timing` turn those reports into numbers. Estimates after synthesis: placement can still change LUT counts and
delays — `options.fpga.implement: true` adds opt_design / place_design / route_design for numbers closer to the board."""

from __future__ import annotations

import re
from pathlib import Path

DEFAULT_PART = "xc7k325tffg900-2"
SDC_ORDER = ("clocks.tcl", "clock_groups.tcl", "io_constraints.tcl", "exceptions.tcl")  # read_xdc order (env.tcl: ASIC only)


def script_text(files: list[Path], top: str, sdc_dir: Path, workdir: Path, options: dict | None = None) -> str:
    """The Vivado Tcl script. `options.fpga`: `part`, `implement` (place and route too), `extra_tcl` (lines before synth),
    `synth_args` (extra `synth_design` arguments), `defines` / `generics` ({name: value})."""
    cfg = (options or {}).get("fpga") or {}
    part = cfg.get("part") or DEFAULT_PART
    lines = [f"# generated by Q3TUI (fpga_synth) — top {top}, part {part}",
             "read_verilog -sv [list " + " ".join(f'"{f}"' for f in files) + "]"]
    for name in SDC_ORDER:
        if (sdc_dir / name).is_file():
            lines.append(f'read_xdc -mode out_of_context "{sdc_dir / name}"')
    lines += [str(x) for x in cfg.get("extra_tcl") or []]
    args = ["-top", top, "-part", part, "-mode", "out_of_context", *map(str, cfg.get("synth_args") or [])]
    args += [f"-verilog_define {k}={v}" if v is not None else f"-verilog_define {k}" for k, v in (cfg.get("defines") or {}).items()]
    args += [f"-generic {k}={v}" for k, v in (cfg.get("generics") or {}).items()]
    lines.append("synth_design " + " ".join(args))
    if cfg.get("implement"):
        lines += ["opt_design", "place_design", "route_design"]
    lines += [f'report_utilization -file "{workdir / "utilization.rpt"}"',
              f'report_timing_summary -delay_type min_max -max_paths 10 -file "{workdir / "timing.rpt"}"',
              f'report_clock_utilization -file "{workdir / "clocks.rpt"}"',
              f'check_timing -verbose -file "{workdir / "check_timing.rpt"}"',
              f'report_timing -delay_type max -max_paths 5 -sort_by slack -file "{workdir / "paths.rpt"}"']
    return "\n".join(lines) + "\n"


# -- reports -------------------------------------------------------------------------------------------------------

_ROW = re.compile(r"^\|\s*(?P<name>[^|]+?)\s*\|\s*(?P<used>[\d.]+)\s*\|\s*(?P<fixed>[\d.]+)\s*\|(?:\s*(?P<prohibited>[\d.]+)\s*\|)?\s*(?P<avail>[\d.]+)\s*\|\s*(?P<pct>[\d.<>=]+)\s*\|")
RESOURCES = {"Slice LUTs": "lut", "Slice LUTs*": "lut", "CLB LUTs": "lut", "CLB LUTs*": "lut", "LUT as Logic": "lut_logic",
             "LUT as Memory": "lut_ram", "Slice Registers": "ff", "CLB Registers": "ff", "Block RAM Tile": "bram_tile",
             "RAMB36/FIFO*": "ramb36", "RAMB18": "ramb18", "DSPs": "dsp", "F7 Muxes": "f7mux", "F8 Muxes": "f8mux",
             "Bonded IOB": "io", "URAM": "uram"}


def parse_utilization(text: str) -> dict:
    """{resource: {used, available, pct}} from report_utilization (the first table row of each resource name wins)."""
    out: dict[str, dict] = {}
    for line in text.splitlines():
        m = _ROW.match(line)
        if not m:
            continue
        key = RESOURCES.get(m["name"].strip())
        if key and key not in out:
            pct = m["pct"].lstrip("<>=")
            out[key] = {"used": float(m["used"]), "available": float(m["avail"]), "pct": float(pct) if pct else 0.0}
    for k, v in out.items():
        for f in ("used", "available"):
            if v[f] == int(v[f]):
                v[f] = int(v[f])
    return out


def _summary_table(text: str) -> tuple[list[str], list[str]] | None:
    """(column names, first data row) of the table under "Design Timing Summary" (columns are 2+ spaces apart)."""
    i = text.find("Design Timing Summary")
    if i < 0:
        return None
    lines = text[i:].splitlines()[1:40]
    for n, line in enumerate(lines):
        if re.match(r"\s*-{3,}(\s+-{3,})+\s*$", line) and n > 0 and lines[n - 1].strip() and n + 1 < len(lines):
            return re.split(r"\s{2,}", lines[n - 1].strip()), lines[n + 1].split()
    return None


_TIMING_COLUMNS = {"WNS(ns)": "wns_ns", "TNS(ns)": "tns_ns", "TNS Failing Endpoints": "failing_endpoints",
                   "TNS Total Endpoints": "endpoints", "WHS(ns)": "whs_ns", "THS(ns)": "ths_ns",
                   "THS Failing Endpoints": "hold_failing_endpoints"}


def parse_timing(text: str) -> dict:
    """Design Timing Summary: setup `wns_ns` / `tns_ns` / `failing_endpoints` / `endpoints`, hold `whs_ns` / `ths_ns` when
    the report has them (after placement), and `met` (the tool's "All user specified timing constraints are met")."""
    out: dict = {}
    tab = _summary_table(text)
    if tab:
        for name, val in zip(*tab):
            key = _TIMING_COLUMNS.get(name)
            if key:
                try:
                    out[key] = int(val) if "endpoints" in key else float(val)
                except ValueError:
                    pass
    out["met"] = "All user specified timing constraints are met" in text
    return out


def critical_path(text: str) -> dict:
    """The worst setup path of `report_timing`: slack, source, destination, logic levels, data path delay."""
    out: dict = {}
    for key, pat in (("slack_ns", r"^\s*Slack(?:\s*\(\w+\))?\s*:\s*(-?[\d.]+)ns"), ("source", r"^\s*Source:\s*(\S+)"),
                     ("destination", r"^\s*Destination:\s*(\S+)"), ("logic_levels", r"^\s*Logic Levels:\s*(\d+)"),
                     ("data_path_ns", r"^\s*Data Path Delay:\s*(-?[\d.]+)ns")):
        m = re.search(pat, text, re.M)
        if m:
            out[key] = float(m.group(1)) if key.endswith("_ns") else (int(m.group(1)) if key == "logic_levels" else m.group(1))
    return out


def unconstrained(text: str) -> dict[str, int]:
    """check_timing: {check name: how many} for the checks that found something (no_input_delay (1) → 1)."""
    out = {}
    for m in re.finditer(r"^\d+\. checking (\w+) \((\d+)\)", text, re.M):
        if int(m.group(2)):
            out[m.group(1)] = int(m.group(2))
    return out


# -- progress while it runs ----------------------------------------------------------------------------------------

_PHASE = re.compile(r"^(?P<what>(?:Starting|Start|Finished|Phase \d+(?:\.\d+)*|Synthesis finished|Running|Parsing|Loading)\b[^:]*?)(?:\s*:\s*Time \(s\).*)?$")


def phase_line(line: str) -> str | None:
    """A line of the Vivado log worth showing as progress ("Start RTL Component Statistics", "Finished Technology Mapping"), else
    None; the timing / memory tail of the line is cut."""
    m = _PHASE.match(line.strip())
    return m["what"].strip()[:100] if m else None


class LogTail:
    """Reads what a growing log file got since the last `new()` (the tool writes it while it runs)."""

    def __init__(self, path: Path):
        self.path, self.pos = path, 0

    def new(self) -> list[str]:
        try:
            with self.path.open("rb") as fh:
                fh.seek(self.pos)
                data = fh.read()
        except OSError:
            return []
        end = data.rfind(b"\n") + 1  # whole lines only
        self.pos += end
        return data[:end].decode(errors="replace").splitlines()
