"""Code-generated parts of the VLSIT testbench: the result macros, the test includes and runner, filelists, run script.

Result format (parsed by `verify`): one line per test case `TC_RESULT <tc_id> PASS|FAIL` (`TC_DETAIL <tc_id> FAIL: <msg>`
for every failed check) and one `TC_SUMMARY total=<n> failed=<n>`."""

from __future__ import annotations

from pathlib import Path

from q3tui.flows.vlsit.tb.plan import file_name, task_name

RESULT_FORMAT = "TC_RESULT <tc_id> PASS|FAIL"

COMMON = """// Generated by Q3TUI (vlsit tb) — included inside the testbench top module. Do not edit.
string tc_id_s;
bit    tc_fail_f;
string tc_sel_s;   // +TC=<tc_id>: run only that test case (no plusarg: all of them)
bit    tc_sel_f;
int    tc_total_n  = 0;
int    tc_failed_n = 0;

// `TC_CHECK(cond, "message")`: a failed check marks the running test case FAIL (the test goes on to its next check)
`define TC_CHECK(cond, msg) if (!(cond)) begin tc_fail_f = 1; $display("TC_DETAIL %s FAIL: %s", tc_id_s, msg); end
`define TC_REPORT begin tc_total_n++; if (tc_fail_f) begin tc_failed_n++; $display("TC_RESULT %s FAIL", tc_id_s); end else $display("TC_RESULT %s PASS", tc_id_s); end
`define TC_SUMMARY $display("TC_SUMMARY total=%0d failed=%0d", tc_total_n, tc_failed_n);
"""

INCLUDES = ('`include "tb_common.svh"', '`include "tb_tests.svh"', '`include "tb_run.svh"')


def tests_include(cases: list[dict]) -> str:
    return "// Generated by Q3TUI (vlsit tb): the selected test cases. Do not edit.\n" + "".join(
        f'`include "tests/{file_name(c)}"\n' for c in cases)


def run_body(cases: list[dict]) -> str:
    """Runs every selected test case in order; included in tb_top's initial block after reset."""
    out = ["// Generated by Q3TUI (vlsit tb): run the selected test cases (`+TC=<tc_id>`: only that one). Do not edit.",
           'tc_sel_f = $value$plusargs("TC=%s", tc_sel_s);']
    for c in cases:
        out.append(f'if (!tc_sel_f || tc_sel_s == "{c["tc_id"]}") begin\ntc_id_s = "{c["tc_id"]}"; tc_fail_f = 0;\n{task_name(c)}();\n`TC_REPORT\nend')
    return "\n".join(out) + "\n"


def write_framework(tb_dir: Path, cases: list[dict]) -> list[Path]:
    (tb_dir / "tests").mkdir(parents=True, exist_ok=True)
    files = {"tb_common.svh": COMMON, "tb_tests.svh": tests_include(cases), "tb_run.svh": run_body(cases)}
    out = []
    for name, text in files.items():
        p = tb_dir / name
        if not p.is_file() or p.read_text() != text:
            p.write_text(text)
        out.append(p)
    return out


def top_problems(text: str) -> list[str]:
    """What tb_top.sv must contain for the generated pieces to work."""
    problems = [f"tb_top must contain the line {inc}" for inc in INCLUDES if inc not in text]
    if "$finish" not in text:
        problems.append("tb_top must end the simulation with $finish after `TC_SUMMARY")
    if "TC_SUMMARY" not in text:
        problems.append("tb_top must print the summary with `TC_SUMMARY after the test cases ran")
    if "module tb_top" not in text:
        problems.append("the testbench top module must be named tb_top")
    return problems


def rtl_files(project_root: Path, rtl_dir: Path) -> list[Path]:
    fl = rtl_dir / "filelist.f"
    if fl.is_file():
        return [(project_root / ln.strip()).resolve() for ln in fl.read_text().splitlines()
                if ln.strip() and not ln.strip().startswith(("//", "#", "+", "-"))]
    return sorted(p.resolve() for p in rtl_dir.glob("*.sv")) if rtl_dir.is_dir() else []


def filelists(project_root: Path, tb_dir: Path, rtl_dir: Path, work: Path, cases: list[dict]) -> tuple[Path, Path, list[Path]]:
    """(deliverable filelist with project-relative paths, absolute one for the tool, the files in it)."""
    rtl = rtl_files(project_root, rtl_dir)
    # only tb_top.sv: the test cases are `include`d into it (tb_tests.svh, found through +incdir) — listed as sources of their
    # own they compile outside tb_top and cannot see its signals or tc_fail_f (a real VCS run: 10 "identifier not declared")
    tb_files = [tb_dir / "tb_top.sv"]
    def rel(p: Path) -> str:
        try:
            return str(p.resolve().relative_to(project_root.resolve()))
        except ValueError:
            return str(p)

    (tb_dir / "filelist.f").write_text("// Generated by Q3TUI (vlsit tb); paths relative to the project root\n"
                                       + "\n".join(rel(p) for p in rtl) + f"\n+incdir+{rel(tb_dir)}\n"
                                       + "\n".join(rel(p) for p in tb_files) + "\n")
    work.mkdir(parents=True, exist_ok=True)
    absf = work / "filelist_tb_abs.f"
    absf.write_text("\n".join(str(p.resolve()) for p in rtl) + f"\n+incdir+{tb_dir.resolve()}\n"
                    + "\n".join(str(p.resolve()) for p in tb_files) + "\n")
    return tb_dir / "filelist.f", absf, [*rtl, *tb_files]


def run_script(compile_cmd: str | None, run_cmd: str | None) -> str:
    return ("#!/bin/sh\n# Generated by Q3TUI (vlsit tb) from the tool roles `sim` and `run`; run from the project root.\n"
            f"# Results: lines `{RESULT_FORMAT}` and `TC_SUMMARY total=<n> failed=<n>`.\nset -e\n"
            f"{compile_cmd or '# (no sim role)'}\n{run_cmd or '# (no run role)'}\n")
